name: Production Build

on:
  release:
    types: [published]

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Dependency Install
        run: npm install

      - name: Build App
        run: npm run build

      - name: Install Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Storage
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'build'
          destination: ${{ vars.GCP_STORAGE_BUCKET_NAME_PROD }}
          parent: false
          predefinedAcl: publicRead
